[package]
name = "cmake-package"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.89"
itertools = "0.13.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
tempfile = "3.13.0"
which = "6.0.3"
