on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: CI

jobs:
  build:
    name: "Build and Test"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          #- macos-latest TODO
      fail-fast: false
    env:
      RUSTFLAGS: "-D warnings"
      RUST_BACKTRACE: full

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
            override: true
      - uses: swatinem/rust-cache@v2
      - name: Build cmake-package
        uses: actions-rs/cargo@v1
        with:
          command: build --all-targets --all-features
      - name: Doctests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --doc --all-features
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Tests
        uses: actions-rs/cargo@v1
        with:
          command: nextest
          args: run --all-features --profile ci
